# Chapter 15 - Regularization

In [1]:
# A technique to improve performance on test data
import pandas as pd

In [2]:
# let's import a dataset

acs = pd.read_csv("C:/Users/adri_/Documents/GitHub- Adriana/Pandas for everyone/data/acs_ny.csv")
acs

,Acres,FamilyIncome,FamilyType,NumBedrooms,NumChildren,NumPeople,NumRooms,NumUnits,NumVehicles,NumWorkers,OwnRent,YearBuilt,HouseCosts,ElectricBill,FoodStamp,HeatingFuel,Insurance,Language
0,1-10,150,Married,4,1,3,9,Single detached,1,0,Mortgage,1950-1959,1800,90,No,Gas,2500,English
1,1-10,180,Female Head,3,2,4,6,Single detached,2,0,Rented,Before 1939,850,90,No,Oil,0,English
2,1-10,280,Female Head,4,0,2,8,Single detached,3,1,Mortgage,2000-2004,2600,260,No,Oil,6600,Other European
3,1-10,330,Female Head,2,1,2,4,Single detached,1,0,Rented,1950-1959,1800,140,No,Oil,0,English
4,1-10,330,Male Head,3,1,2,5,Single attached,1,0,Mortgage,Before 1939,860,150,No,Gas,660,Spanish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22740,10+,565000,Married,5,3,5,10,Single detached,2,2,Mortgage,1990-1999,1700,370,No,Gas,1000,English
22741,10+,599000,Married,4,0,2,6,Single detached,2,2,Mortgage,Before 1939,1300,100,No,Gas,3500,English
22742,10+,611700,Married,4,1,5,9,Single detached,5,3,Mortgage,Before 1939,410,100,No,Oil,1300,Spanish
22743,10+,621430,Married,3,2,4,11,Single detached,2,3,Mortgage,1970-1979,1600,80,No,Gas,800,Spanish
22744,10+,751200,Married,4,2,4,10,Single detached,2,2,Mortgage,1940-1949,6500,400,No,Oil,2000,English

In [3]:
#let's see the columns

acs.columns

Index(['Acres', 'FamilyIncome', 'FamilyType', 'NumBedrooms', 'NumChildren',
       'NumPeople', 'NumRooms', 'NumUnits', 'NumVehicles', 'NumWorkers',
       'OwnRent', 'YearBuilt', 'HouseCosts', 'ElectricBill', 'FoodStamp',
       'HeatingFuel', 'Insurance', 'Language'],
      dtype='object')

In [4]:
#let's use patsy to create the designs
from patsy import dmatrices

In [5]:
# model

response,predictors, = dmatrices("FamilyIncome ~ NumBedrooms + NumChildren + NumPeople + NumRooms + NumUnits + NumVehicles + NumWorkers + OwnRent + YearBuilt + ElectricBill + FoodStamp +HeatingFuel + Insurance + Language", data = acs)

In [6]:
# Splitting the data ino training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors, response, random_state = 0)

In [7]:
# fitting our model

from sklearn.linear_model import LinearRegression

lr = LinearRegression(normalize = True).fit(X_train, y_train)

model_coefs = pd.DataFrame(list(zip(predictors.design_info.column_names,lr.coef_[0])), columns = ["variable", "coef_lr"])

model_coefs

                       variable       coef_lr
0                     Intercept  3.522660e-11
1   NumUnits[T.Single attached]  3.135646e+04
2   NumUnits[T.Single detached]  2.418368e+04
3           OwnRent[T.Outright]  2.839186e+04
4             OwnRent[T.Rented]  7.229586e+03
5        YearBuilt[T.1940-1949]  1.292169e+04
6        YearBuilt[T.1950-1959]  2.057793e+04
7        YearBuilt[T.1960-1969]  1.764835e+04
8        YearBuilt[T.1970-1979]  1.756881e+04
9        YearBuilt[T.1980-1989]  2.552566e+04
10       YearBuilt[T.1990-1999]  2.983944e+04
11       YearBuilt[T.2000-2004]  3.012502e+04
12            YearBuilt[T.2005]  4.318648e+04
13            YearBuilt[T.2006]  3.242038e+04
14            YearBuilt[T.2007]  3.562061e+04
15            YearBuilt[T.2008]  3.712470e+04
16            YearBuilt[T.2009]  3.035133e+04
17            YearBuilt[T.2010]  7.364529e+04
18     YearBuilt[T.Before 1939]  1.218711e+04
19             FoodStamp[T.Yes] -2.745712e+04
20   HeatingFuel[T.Electricity]  1.946552e+04
21           HeatingFuel[T.Gas]  2.588482e+04
22          HeatingFuel[T.None]  2.532452e+04
23           HeatingFuel[T.Oil]  2.535803e+04
24         HeatingFuel[T.Other]  1.734533e+04
25         HeatingFuel[T.Solar]  8.424991e+03
26          HeatingFuel[T.Wood]  8.898002e+02
27          Language[T.English] -1.873624e+04
28            Language[T.Other] -4.463333e+03
29   Language[T.Other European] -1.409466e+04
30          Language[T.Spanish] -2.603347e+04
31                  NumBedrooms  3.443931e+03
32                  NumChildren  8.215723e+03
33                    NumPeople -8.203826e+03
34                     NumRooms  5.735494e+03
35                  NumVehicles  7.484535e+03
36                   NumWorkers  2.283630e+04
37                 ElectricBill  9.332524e+01
38                    Insurance  3.099441e+01

In [8]:
# Now we can look at our model scores
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

0.2726140465638567
0.26976979568488124

# 15.3 Lasso regression (Least Absolute Shrinkage and Selection Operator)

In [9]:
from sklearn.linear_model import Lasso

In [10]:
#Create model

lasso = Lasso(normalize = True, random_state = 0).fit(X_test,y_test)

In [11]:
# Getting a dataframe of coefficients
coefs_lasso = pd.DataFrame(list(zip(predictors.design_info.column_names, lasso.coef_)), columns = ["variable", "coef_lasso"])

In [12]:
# Merging

model_coefs = pd.merge(model_coefs, coefs_lasso, on="variable")
model_coefs

                       variable       coef_lr    coef_lasso
0                     Intercept  3.522660e-11      0.000000
1   NumUnits[T.Single attached]  3.135646e+04  23847.097905
2   NumUnits[T.Single detached]  2.418368e+04  20278.620009
3           OwnRent[T.Outright]  2.839186e+04  30153.611697
4             OwnRent[T.Rented]  7.229586e+03   1440.140884
5        YearBuilt[T.1940-1949]  1.292169e+04  -6382.312453
6        YearBuilt[T.1950-1959]  2.057793e+04   -905.142030
7        YearBuilt[T.1960-1969]  1.764835e+04     -0.000000
8        YearBuilt[T.1970-1979]  1.756881e+04  -1579.827129
9        YearBuilt[T.1980-1989]  2.552566e+04   7854.066748
10       YearBuilt[T.1990-1999]  2.983944e+04   1355.026160
11       YearBuilt[T.2000-2004]  3.012502e+04  11212.207583
12            YearBuilt[T.2005]  4.318648e+04   8770.315635
13            YearBuilt[T.2006]  3.242038e+04  34814.310436
14            YearBuilt[T.2007]  3.562061e+04  27415.800873
15            YearBuilt[T.2008]  3.712470e+04  10866.123988
16            YearBuilt[T.2009]  3.035133e+04    312.110532
17            YearBuilt[T.2010]  7.364529e+04  10093.244533
18     YearBuilt[T.Before 1939]  1.218711e+04  -4903.325664
19             FoodStamp[T.Yes] -2.745712e+04 -23717.406880
20   HeatingFuel[T.Electricity]  1.946552e+04   1775.625749
21           HeatingFuel[T.Gas]  2.588482e+04  12410.061671
22          HeatingFuel[T.None]  2.532452e+04  -4153.735420
23           HeatingFuel[T.Oil]  2.535803e+04  10009.595676
24         HeatingFuel[T.Other]  1.734533e+04  -6803.711978
25         HeatingFuel[T.Solar]  8.424991e+03      0.000000
26          HeatingFuel[T.Wood]  8.898002e+02  -9398.444417
27          Language[T.English] -1.873624e+04  -8076.201004
28            Language[T.Other] -4.463333e+03 -21403.661071
29   Language[T.Other European] -1.409466e+04  -9113.511553
30          Language[T.Spanish] -2.603347e+04 -14321.350716
31                  NumBedrooms  3.443931e+03   3976.075383
32                  NumChildren  8.215723e+03   5652.313652
33                    NumPeople -8.203826e+03  -5903.547002
34                     NumRooms  5.735494e+03   4612.117329
35                  NumVehicles  7.484535e+03   7736.529456
36                   NumWorkers  2.283630e+04  20346.201513
37                 ElectricBill  9.332524e+01     89.504660
38                    Insurance  3.099441e+01     31.954902

In [13]:
# Looking at our training and test data scores

print(lasso.score(X_train, y_train))
print(lasso.score(X_test, y_test))

0.26670104659430227
0.27506204638605314

# 15.4 Ridge Regression

In [14]:
from sklearn.linear_model import Ridge

ridge = Ridge(normalize = True, random_state = 0).fit(X_train, y_train)
coefs_ridge = pd.DataFrame(list(zip(predictors.design_info.column_names, ridge.coef_[0])), columns = ["variable", "coef_ridge"])

modeL_coefs = pd.merge(model_coefs, coefs_ridge, on= "variable")
model_coefs

                       variable       coef_lr    coef_lasso
0                     Intercept  3.522660e-11      0.000000
1   NumUnits[T.Single attached]  3.135646e+04  23847.097905
2   NumUnits[T.Single detached]  2.418368e+04  20278.620009
3           OwnRent[T.Outright]  2.839186e+04  30153.611697
4             OwnRent[T.Rented]  7.229586e+03   1440.140884
5        YearBuilt[T.1940-1949]  1.292169e+04  -6382.312453
6        YearBuilt[T.1950-1959]  2.057793e+04   -905.142030
7        YearBuilt[T.1960-1969]  1.764835e+04     -0.000000
8        YearBuilt[T.1970-1979]  1.756881e+04  -1579.827129
9        YearBuilt[T.1980-1989]  2.552566e+04   7854.066748
10       YearBuilt[T.1990-1999]  2.983944e+04   1355.026160
11       YearBuilt[T.2000-2004]  3.012502e+04  11212.207583
12            YearBuilt[T.2005]  4.318648e+04   8770.315635
13            YearBuilt[T.2006]  3.242038e+04  34814.310436
14            YearBuilt[T.2007]  3.562061e+04  27415.800873
15            YearBuilt[T.2008]  3.712470e+04  10866.123988
16            YearBuilt[T.2009]  3.035133e+04    312.110532
17            YearBuilt[T.2010]  7.364529e+04  10093.244533
18     YearBuilt[T.Before 1939]  1.218711e+04  -4903.325664
19             FoodStamp[T.Yes] -2.745712e+04 -23717.406880
20   HeatingFuel[T.Electricity]  1.946552e+04   1775.625749
21           HeatingFuel[T.Gas]  2.588482e+04  12410.061671
22          HeatingFuel[T.None]  2.532452e+04  -4153.735420
23           HeatingFuel[T.Oil]  2.535803e+04  10009.595676
24         HeatingFuel[T.Other]  1.734533e+04  -6803.711978
25         HeatingFuel[T.Solar]  8.424991e+03      0.000000
26          HeatingFuel[T.Wood]  8.898002e+02  -9398.444417
27          Language[T.English] -1.873624e+04  -8076.201004
28            Language[T.Other] -4.463333e+03 -21403.661071
29   Language[T.Other European] -1.409466e+04  -9113.511553
30          Language[T.Spanish] -2.603347e+04 -14321.350716
31                  NumBedrooms  3.443931e+03   3976.075383
32                  NumChildren  8.215723e+03   5652.313652
33                    NumPeople -8.203826e+03  -5903.547002
34                     NumRooms  5.735494e+03   4612.117329
35                  NumVehicles  7.484535e+03   7736.529456
36                   NumWorkers  2.283630e+04  20346.201513
37                 ElectricBill  9.332524e+01     89.504660
38                    Insurance  3.099441e+01     31.954902

# 15.5 Elastic Net

In [15]:
from sklearn.linear_model import ElasticNet

en = ElasticNet(random_state = 42).fit(X_train, y_train)

coefs_en = pd.DataFrame(list(zip(predictors.design_info.column_names, en.coef_)), columns = ["variable", "coef_en"])

modeL_coefs = pd.merge(model_coefs, coefs_en, on= "variable")
model_coefs

                       variable       coef_lr    coef_lasso
0                     Intercept  3.522660e-11      0.000000
1   NumUnits[T.Single attached]  3.135646e+04  23847.097905
2   NumUnits[T.Single detached]  2.418368e+04  20278.620009
3           OwnRent[T.Outright]  2.839186e+04  30153.611697
4             OwnRent[T.Rented]  7.229586e+03   1440.140884
5        YearBuilt[T.1940-1949]  1.292169e+04  -6382.312453
6        YearBuilt[T.1950-1959]  2.057793e+04   -905.142030
7        YearBuilt[T.1960-1969]  1.764835e+04     -0.000000
8        YearBuilt[T.1970-1979]  1.756881e+04  -1579.827129
9        YearBuilt[T.1980-1989]  2.552566e+04   7854.066748
10       YearBuilt[T.1990-1999]  2.983944e+04   1355.026160
11       YearBuilt[T.2000-2004]  3.012502e+04  11212.207583
12            YearBuilt[T.2005]  4.318648e+04   8770.315635
13            YearBuilt[T.2006]  3.242038e+04  34814.310436
14            YearBuilt[T.2007]  3.562061e+04  27415.800873
15            YearBuilt[T.2008]  3.712470e+04  10866.123988
16            YearBuilt[T.2009]  3.035133e+04    312.110532
17            YearBuilt[T.2010]  7.364529e+04  10093.244533
18     YearBuilt[T.Before 1939]  1.218711e+04  -4903.325664
19             FoodStamp[T.Yes] -2.745712e+04 -23717.406880
20   HeatingFuel[T.Electricity]  1.946552e+04   1775.625749
21           HeatingFuel[T.Gas]  2.588482e+04  12410.061671
22          HeatingFuel[T.None]  2.532452e+04  -4153.735420
23           HeatingFuel[T.Oil]  2.535803e+04  10009.595676
24         HeatingFuel[T.Other]  1.734533e+04  -6803.711978
25         HeatingFuel[T.Solar]  8.424991e+03      0.000000
26          HeatingFuel[T.Wood]  8.898002e+02  -9398.444417
27          Language[T.English] -1.873624e+04  -8076.201004
28            Language[T.Other] -4.463333e+03 -21403.661071
29   Language[T.Other European] -1.409466e+04  -9113.511553
30          Language[T.Spanish] -2.603347e+04 -14321.350716
31                  NumBedrooms  3.443931e+03   3976.075383
32                  NumChildren  8.215723e+03   5652.313652
33                    NumPeople -8.203826e+03  -5903.547002
34                     NumRooms  5.735494e+03   4612.117329
35                  NumVehicles  7.484535e+03   7736.529456
36                   NumWorkers  2.283630e+04  20346.201513
37                 ElectricBill  9.332524e+01     89.504660
38                    Insurance  3.099441e+01     31.954902

# 15.6 Cross-validation

In [16]:
from sklearn.linear_model import ElasticNetCV

en_cv = ElasticNetCV(cv = 5, random_state = 42).fit(X_train, y_train)

coefs_en_cv = pd.DataFrame(list(zip(predictors.design_info.column_names, en_cv.coef_)), columns = ["variable", "coef_en_cv"])

modeL_coefs = pd.merge(model_coefs, coefs_en_cv, on= "variable")
model_coefs

C:\Users\adri_\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

                       variable       coef_lr    coef_lasso
0                     Intercept  3.522660e-11      0.000000
1   NumUnits[T.Single attached]  3.135646e+04  23847.097905
2   NumUnits[T.Single detached]  2.418368e+04  20278.620009
3           OwnRent[T.Outright]  2.839186e+04  30153.611697
4             OwnRent[T.Rented]  7.229586e+03   1440.140884
5        YearBuilt[T.1940-1949]  1.292169e+04  -6382.312453
6        YearBuilt[T.1950-1959]  2.057793e+04   -905.142030
7        YearBuilt[T.1960-1969]  1.764835e+04     -0.000000
8        YearBuilt[T.1970-1979]  1.756881e+04  -1579.827129
9        YearBuilt[T.1980-1989]  2.552566e+04   7854.066748
10       YearBuilt[T.1990-1999]  2.983944e+04   1355.026160
11       YearBuilt[T.2000-2004]  3.012502e+04  11212.207583
12            YearBuilt[T.2005]  4.318648e+04   8770.315635
13            YearBuilt[T.2006]  3.242038e+04  34814.310436
14            YearBuilt[T.2007]  3.562061e+04  27415.800873
15            YearBuilt[T.2008]  3.712470e+04  10866.123988
16            YearBuilt[T.2009]  3.035133e+04    312.110532
17            YearBuilt[T.2010]  7.364529e+04  10093.244533
18     YearBuilt[T.Before 1939]  1.218711e+04  -4903.325664
19             FoodStamp[T.Yes] -2.745712e+04 -23717.406880
20   HeatingFuel[T.Electricity]  1.946552e+04   1775.625749
21           HeatingFuel[T.Gas]  2.588482e+04  12410.061671
22          HeatingFuel[T.None]  2.532452e+04  -4153.735420
23           HeatingFuel[T.Oil]  2.535803e+04  10009.595676
24         HeatingFuel[T.Other]  1.734533e+04  -6803.711978
25         HeatingFuel[T.Solar]  8.424991e+03      0.000000
26          HeatingFuel[T.Wood]  8.898002e+02  -9398.444417
27          Language[T.English] -1.873624e+04  -8076.201004
28            Language[T.Other] -4.463333e+03 -21403.661071
29   Language[T.Other European] -1.409466e+04  -9113.511553
30          Language[T.Spanish] -2.603347e+04 -14321.350716
31                  NumBedrooms  3.443931e+03   3976.075383
32                  NumChildren  8.215723e+03   5652.313652
33                    NumPeople -8.203826e+03  -5903.547002
34                     NumRooms  5.735494e+03   4612.117329
35                  NumVehicles  7.484535e+03   7736.529456
36                   NumWorkers  2.283630e+04  20346.201513
37                 ElectricBill  9.332524e+01     89.504660
38                    Insurance  3.099441e+01     31.954902